<?php

function visitor_info_menu() {
	$items = array();
	$items[] = array(
		'path' => 'contact',
		'title' => t('Contact Information'),
		'page callback' => 'visitor_info_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK
	);
	return $items;
}


function visitor_info_page() {
	return drupal_get_form('visitor_info_contact_form');
}

function visitor_info_contact_form($form_state) {
	$form = array();
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Full Name'),
		'#description' => t('Your full name in the format first-name middle-name last-name'),
		'#required' => TRUE,
	);
	$form['age'] = array(
		'#type' => 'textfield',
		'#title' => t('Age'),
		'#required' => TRUE,
	);
	$form['income'] = array(
		'#type' => 'textfield',
		'#title' => t('Annual Income'),
		'#description' => t('Your annual income - total income for the whole year.'),
		'#required' => TRUE,
	);
	$form['city'] = array(
		'#type' => 'textfield',
		'#title' => t('City'),
		'#required' => TRUE,
	);
	$form['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email address'),
	);
	$form['phone'] = array(
		'#type' => 'textfield',
		'#title' => t('Phone number'),
		'#required' => TRUE,
	);
	$form['time_to_call'] = array(
		'#type' => 'textfield',
		'#title' => t('Best time to call'),
		'#description' => t('Ex. 1pm - 2pm on Saturdays.'),
		'#required' => TRUE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return $form;
}

function visitor_info_contact_form_submit($form, &$form_state) {
	db_query("INSERT INTO {visitor_info} (name,age, income, email, phone, time_to_call, city, time_of_visit) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', %d)", $form_state['values']['name'], $form_state['values']['age'], $form_state['values']['income'], $form_state['values']['email'], $form_state['values']['phone'], $form_state['values']['time_to_call'], $form_state['values']['city'], $form_state['values']['time_of_visit']);
	drupal_set_message(t('Your form has been saved.'));
}
