<?php

function visitor_info_menu() {
	$items = array();
	$items[] = array(
		'path' => 'contact',
		'title' => t('Contact Information'),
		'page callback' => 'visitor_info_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK
	);
	return $items;
}


function visitor_info_page() {
	return drupal_get_form('visitor_info_contact_form');
}

function visitor_info_contact_form($form_state) {
	$form = array();
	$form['name'] = array(
		'#type' => 'textfield',
		'#title' => t('Full Name'),
		'#description' => t('Your full name in the format first-name middle-name last-name'),
		'#required' => TRUE,
	);
	$form['age'] = array(
		'#type' => 'textfield',
		'#title' => t('Age'),
		'#required' => TRUE,
	);
	$form['income'] = array(
		'#type' => 'textfield',
		'#title' => t('Annual Income'),
		'#description' => t('Your annual income - total income for the whole year.'),
		'#required' => TRUE,
	);
	$form['city'] = array(
		'#type' => 'textfield',
		'#title' => t('City'),
		'#required' => TRUE,
	);
	$form['email'] = array(
		'#type' => 'textfield',
		'#title' => t('Email address'),
	);
	$form['phone'] = array(
		'#type' => 'textfield',
		'#title' => t('Phone number'),
		'#required' => TRUE,
	);
	$form['time_to_call'] = array(
		'#type' => 'textfield',
		'#title' => t('Best time to call'),
		'#description' => t('Ex. 1pm - 2pm on Saturdays.'),
		'#required' => TRUE,
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return $form;
}

function visitor_info_contact_form_submit($form, &$form_state) {
	$record = array(
		'name' => $form_state['values']['name'],
		'age' => $form_state['values']['age'],
		'income' => $form_state['values']['income'],
		'email' => $form_state['values']['email'],
		'phone' => $form_state['values']['phone'],
		'time_to_call' => $form_state['values']['time_to_call'],
		'city' => $form_state['values']['city'],
		'time_of_visit' => time()
	);
	drupal_write_record('visitor_info',$record);
	drupal_set_message(t('Your form has been saved.'));
}
